services:
  postgres:
    image: postgis/postgis:18-3.6-alpine
    container_name: dokabiliteetti_postgres
    env_file: .env
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dokabiliteetti_network

volumes:
  postgres_data:
    driver: local

networks:
  dokabiliteetti_network:
    driver: bridge
